import Head from 'next/head'
import { Anek_Devanagari } from 'next/font/google'
import ExampleForm from '@/components/ExampleForm'

const inter = Anek_Devanagari({ subsets: ['devanagari'], weight: "600" })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ExampleForm />
    </>
  )
}
